export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP';
export const CREATION_PREVIOUS_STEP = 'CREATION_PREVIOUS_STEP';
export const CREATION_CALENDAR_SELECT_DATE = 'CREATION_CALENDAR_SELECT_DATE';
export const CREATION_CHANGE_TITLE = 'CREATION_CHANGE_TITLE';
export const CREATION_CHANGE_DESCRIPTION = 'CREATION_CHANGE_DESCRIPTION';
export const CREATION_CHANGE_LOCATION = 'CREATION_CHANGE_LOCATION';
export const CREATION_STEP1_TITLE_ERROR = 'CREATION_STEP1_TITLE_ERROR';
export const CREATION_EVENT_UPSERT_REQUEST = 'CREATION_EVENT_UPSERT_REQUEST';
export const CREATION_EVENT_UPSERT_SUCCESS = 'CREATION_EVENT_UPSERT_SUCCESS';
export const CREATION_EVENT_UPSERT_FAILURE = 'CREATION_EVENT_UPSERT_FAILURE';

export const PARTICIPATION_NAME_ONCHANGE = 'PARTICIPATION_CHANGE_NAME';
export const PARTICIPATION_NAME_ONBLUR = 'PARTICIPATION_NAME_ONBLUR';
export const PARTICIPATION_SHOW_DATE_DETAIL = 'PARTICIPATION_SHOW_DATE_DETAIL';
export const PARTICIPATION_EXIT_DATE_DETAIL = 'PARTICIPATION_EXIT_DATE_DETAIL';
export const PARTICIPATION_CHECK_DATE = 'PARTICIPATION_CHECK_DATE';
export const PARTICIPATION_NAME_CHECK = 'PARTICIPATION_NAME_CHECK';
export const PARTICIPATION_UPSERT_REQUEST = 'PARTICIPATION_UPSERT_REQUEST';
export const PARTICIPATION_UPSERT_SUCCESS = 'PARTICIPATION_UPSERT_SUCCESS';
export const PARTICIPATION_UPSERT_FAILURE = 'PARTICIPATION_UPSERT_FAILURE';
export const PARTICIPATION_GO_BACK_AND_EDIT = 'PARTICIPATION_GO_BACK_AND_EDIT';

export const ADMIN_SHOW_EVENT_DATE_DETAIL = 'ADMIN_SHOW_EVENT_DATE_DETAIL';
export const ADMIN_EXIT_EVENT_DATE_DETAIL = 'ADMIN_EXIT_EVENT_DATE_DETAIL';
export const ADMIN_FETCH_EVENT_DATE_DDAY_REQUEST = 'ADMIN_FETCH_EVENT_DATE_DDAY_REQUEST';
export const ADMIN_FETCH_EVENT_DATE_DDAY_SUCCESS = 'ADMIN_FETCH_EVENT_DATE_DDAY_SUCCESS';
export const ADMIN_FETCH_EVENT_DATE_DDAY_FAILURE = 'ADMIN_FETCH_EVENT_DATE_DDAY_FAILURE';

export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';
