export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP';
export const CREATION_PREVIOUS_STEP = 'CREATION_PREVIOUS_STEP';
export const CREATION_CALENDAR_SELECT_DATE = 'CREATION_CALENDAR_SELECT_DATE';
export const CREATION_CHANGE_TITLE = 'CREATION_CHANGE_TITLE';
export const CREATION_CHANGE_DESCRIPTION = 'CREATION_CHANGE_DESCRIPTION';
export const CREATION_CHANGE_LOCATION = 'CREATION_CHANGE_LOCATION';
export const CREATION_STEP1_TITLE_ERROR = 'CREATION_STEP1_TITLE_ERROR';
