export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP';
export const CREATION_PREVIOUS_STEP = 'CREATION_PREVIOUS_STEP';
export const CREATION_CALENDAR_SELECT_DATE = 'CREATION_CALENDAR_SELECT_DATE';
export const CREATION_CHANGE_TITLE = 'CREATION_CHANGE_TITLE';
export const CREATION_CHANGE_DESCRIPTION = 'CREATION_CHANGE_DESCRIPTION';
export const CREATION_CHANGE_LOCATION = 'CREATION_CHANGE_LOCATION';
export const CREATION_STEP1_TITLE_ERROR = 'CREATION_STEP1_TITLE_ERROR';
export const CREATION_EVENT_UPSERT_REQUEST = 'CREATION_EVENT_UPSERT_REQUEST';
export const CREATION_EVENT_UPSERT_SUCCESS = 'CREATION_EVENT_UPSERT_SUCCESS';
export const CREATION_EVENT_UPSERT_FAILURE = 'CREATION_EVENT_UPSERT_FAILURE';

export const PARTICIPATION_NAME_ONCHANGE = 'PARTICIPATION_CHANGE_NAME';
export const PARTICIPATION_NAME_ONBLUR = 'PARTICIPATION_NAME_ONBLUR';
export const PARTICIPATION_SHOW_DATE_DETAIL = 'PARTICIPATION_SHOW_DATE_DETAIL';
export const PARTICIPATION_EXIT_DATE_DETAIL = 'PARTICIPATION_EXIT_DATE_DETAIL';
export const PARTICIPATION_CHECK_DATE = 'PARTICIPATION_CHECK_DATE';

export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';
